steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        timedatectl set-timezone Europe/Copenhagen
        docker build \
          -t $_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/app:latest \
          --cache-from $_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/app:latest \
          --build-arg BUILD_TAG_NAME=$TAG_NAME \
          --build-arg BUILD_SHORT_SHA=$SHORT_SHA \
          --build-arg BUILD_DATE="$$(date '+%F %H:%M:%S')" \
          -f docker/Dockerfile \
          .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/app:latest
    id: Push
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/app:latest
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: europe-west3-docker.pkg.dev
  _SERVICE_NAME: kubernetes-service-orchestrator
timeout: 1200s
