services:

  deploy:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GKE_AUTH_ENABLED: "${KSO_GKE_AUTH_ENABLED}"

    container_name: 4s-deploy-service-app
    restart: unless-stopped
    tty: true

    working_dir: /var/www/html

    ports:
      - "${KSO_CI4_PORT}:80"
      - "${KSO_VUE_PORT}:8901"
      - "${KSO_ZMQ_PORT}:9100"

    environment:
      - ENVIRONMENT=development
      - BASE_URL=http://localhost:${KSO_CI4_PORT}
      - DB_HOST=${KSO_DB_HOST}
      - DB_NAME=${KSO_DB_NAME}
      - DB_USER=${KSO_DB_USER}
      - DB_PASS=${KSO_DB_PASS}
      - ZMQ_EXTERNAL_URL=ws://localhost:${KSO_ZMQ_PORT}
      - CERT_MANAGER_ISSUER_DEFAULT_NAME=${CONFIG_DEFAULTS_CERT_MANAGER_ISSUER_DEFAULT_NAME}
      - IMAGE_PULL_SECRET_DEFAULT_NAME=${CONFIG_DEFAULTS_IMAGE_PULL_SECRET_DEFAULT_NAME}
      - EMAIL_SERVICE_HOST=${CONFIG_EMAIL_HOST}
      - EMAIL_SERVICE_PORT=${CONFIG_EMAIL_PORT}
      - EMAIL_SERVICE_USER=${CONFIG_EMAIL_USER}
      - EMAIL_SERVICE_PASS=${CONFIG_EMAIL_PASS}
      - EMAIL_SERVICE_SENDER=${CONFIG_EMAIL_SENDER}

    volumes:
      - ./:/var/www/html:delegated

    networks:
      - deploy-service-network

  db:
    image: mysql:5.7.25
    container_name: 4s-deploy-service-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DATABASE_PORT}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
      - ./docker/mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d/:delegated

    networks:
      - deploy-service-network

#  mssql:
#    build: ./docker/mssql
#    ports:
#      - "${DATABASE_MSSQL_PORT}:1433"
#    environment:
#      MSSQL_SA_PASSWORD: yTyQLXjH7uOXqwOowPK0@
#    networks:
#      - deploy-service-network

# Docker Networks
networks:
  deploy-service-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
