<?php namespace App\Libraries\DeploymentSteps;

use App\Entities\ContainerImage;
use App\Entities\DatabaseService;
use App\Entities\Deployment;
use App\Entities\DeploymentSpecificationInitContainer;
use App\Entities\DeploymentSpecificationVolume;
use App\Entities\DeploymentVolume;
use App\Entities\MigrationJob;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepHelper;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepLevels;
use App\Libraries\DeploymentSteps\Helpers\DeploymentSteps;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepTriggers;
use App\Libraries\Kubernetes\ContainerEnvironment;
use App\Libraries\Kubernetes\SecretPreview;
use App\Libraries\Kubernetes\WorkloadSecret;
use App\Libraries\Kubernetes\ImagePullSecrets;
use App\Libraries\Kubernetes\KubeAuth;
use App\Libraries\Kubernetes\KubeHelper;
use App\Models\ContainerImageModel;
use App\Models\DeploymentSpecificationInitContainerModel;
use App\Models\DeploymentSpecificationVolumeModel;
use App\Models\DeploymentVolumeModel;
use App\Models\InitContainerModel;
use DebugTool\Data;
use RenokiCo\PhpK8s\Exceptions\KubernetesAPIException;
use RenokiCo\PhpK8s\Instances\Container;
use RenokiCo\PhpK8s\Instances\Volume;
use RenokiCo\PhpK8s\Kinds\K8sEvent;
use RenokiCo\PhpK8s\Kinds\K8sJob;
use RenokiCo\PhpK8s\Kinds\K8sPod;

class MigrationJobStep extends BaseDeploymentStep {

    /**
     * The job's callback token, from the job's Secret - see `MigrationJob::issueCallbackToken()`.
     * Read by the shell rather than substituted by Kubernetes, so it is not in the container's
     * arguments either.
     */
    public const string CallbackTokenVariable = 'MIGRATION_JOB_TOKEN';
    private const string CallbackTokenHeaderArgument = '-H "' . \App\Controllers\MigrationJobs::TokenHeader . ': $' . self::CallbackTokenVariable . '"';

    public function getIdentifier(): string {
        return DeploymentSteps::Migration;
    }

    public function getLevel(): string {
        return DeploymentStepLevels::Deployment;
    }

    public function getName(): string {
        return 'Migration Job';
    }

    public function getTriggers(): array {
        return [
            DeploymentStepTriggers::Deployment_Version_Updated,
            DeploymentStepTriggers::Deployment_ImagePullPolicy_Updated,
        ];
    }

    public function hasPreviewCommand(): bool {
        return true;
    }

    public function hasStatusCommand(): bool {
        return true;
    }

    public function hasDeployCommand(): bool {
        return true;
    }

    public function hasTerminateCommand(): bool {
        return true;
    }

    public function hasKubernetesEvents(): bool {
        return false;
    }

    public function hasKubernetesStatus(): bool {
        return true;
    }

    public function getSuccessStatus(Deployment $deployment): string {
        return DeploymentStepHelper::MigrationJob_Completed;
    }

    /**
     * @throws \Exception
     */
    public function getPreview(Deployment $deployment): string {
        $resource = $this->getResource($deployment, true);
        $local = $resource->toJson();

        if ($resource->exists()) {
            $exiting = $resource->get();
            $remote = json_decode($exiting->toJson(), true);
            unset($remote['metadata']['uid']);
            unset($remote['metadata']['resourceVersion']);
            unset($remote['metadata']['generation']);
            unset($remote['metadata']['creationTimestamp']);
            unset($remote['metadata']['annotations']);
            unset($remote['metadata']['managedFields']);

            // The labels the Job controller copies up from the template, plus its own
            // `controller-uid` and `job-name`. Nothing here was written by kso.
            unset($remote['metadata']['labels']);

            // This step builds a **Job**. The list used to be `spec.jobTemplate.*` with
            // `concurrencyPolicy` and the two history limits beside it - CronJob fields, on
            // a resource that has none of them, so every one of those `unset()` calls did
            // nothing. It reads like a copy of `CronjobStep::getPreview()` that was never
            // rebased.
            //
            // What did reach the diff was the Job's own defaults, filled in by the api
            // server: a preview of a migration showed half a dozen removals the user could
            // not do anything about, every single time.
            unset($remote['spec']['parallelism']);
            unset($remote['spec']['completions']);
            unset($remote['spec']['backoffLimit']);
            unset($remote['spec']['completionMode']);
            unset($remote['spec']['podReplacementPolicy']);
            unset($remote['spec']['manualSelector']);
            unset($remote['spec']['suspend']);

            // Generated by the controller from the job's uid, and kso sets no selector of
            // its own on a Job.
            unset($remote['spec']['selector']);

            // The same paths the cron job step strips, one level shallower: a Job's template
            // is `spec.template`, a CronJob's is `spec.jobTemplate.spec.template`.
            unset($remote['spec']['template']['metadata']);
            unset($remote['spec']['template']['spec']['containers'][0]['resources']);
            unset($remote['spec']['template']['spec']['containers'][0]['terminationMessagePath']);
            unset($remote['spec']['template']['spec']['containers'][0]['terminationMessagePolicy']);
            unset($remote['spec']['template']['spec']['terminationGracePeriodSeconds']);
            unset($remote['spec']['template']['spec']['dnsPolicy']);
            unset($remote['spec']['template']['spec']['schedulerName']);

            // Only when kso expressed no opinion. The api server writes an empty
            // `securityContext` for a pod spec that has none, and that empty object is
            // noise - but a deployment whose image asks for an `fsGroup` does set one, and
            // stripping it then would hide a difference that matters.
            if (!isset(json_decode($local, true)['spec']['template']['spec']['securityContext'])) {
                unset($remote['spec']['template']['spec']['securityContext']);
            }

            unset($remote['status']);
        }

        // The callback token is written by each run and is in no manifest kso builds, so it
        // would be a difference in every preview that nobody can act on.
        $remoteSecretData = $this->workloadSecret->remoteData($deployment, (new KubeAuth())->authenticate());
        if ($remoteSecretData !== null) {
            $remoteSecretData = array_filter(
                $remoteSecretData,
                fn (string $key) => !str_ends_with($key, '.' . self::CallbackTokenVariable),
                ARRAY_FILTER_USE_KEY
            ) ?: null;
        }

        return json_encode(SecretPreview::of(
            $local,
            $remote ?? null,
            $this->workloadSecret,
            $deployment,
            $remoteSecretData
        ));
    }

    /**
     * @throws KubernetesAPIException
     * @throws \Exception
     */
    public function getStatus(Deployment $deployment): string {
        $resource = $this->getResource($deployment, true);
        if (!$resource->exists()) {
            return DeploymentStepHelper::MigrationJob_NotFound;
        }

        try {
            /** @var K8sJob $resource */
            $resource = $resource->get();
        } catch (KubernetesAPIException $e) {
            // Asking whether it is there and then asking for it are two calls, and a job
            // being cleaned up disappears between them - which is the ordinary case right
            // after a terminate. A status call is not the place to throw about that.
            if ($e->getCode() === KubeHelper::NotFoundCode) {
                return DeploymentStepHelper::MigrationJob_NotFound;
            }

            throw $e;
        }

        if ($resource->getStatus('completionTime')) {
            return DeploymentStepHelper::MigrationJob_Completed;
        }

        return DeploymentStepHelper::MigrationJob_Running;
    }

    public function validateDeployCommand(Deployment $deployment): ?string {
        if (strlen($deployment->name) == 0) {
            return 'Missing name';
        }
        if (strlen($deployment->namespace) == 0) {
            return 'Missing namespace';
        }
        if (strlen($deployment->image) == 0) {
            return 'Missing image';
        }
        if (strlen($deployment->version) == 0) {
            return 'Missing version';
        }

        if (!$deployment->database_service_id) {
            return 'Missing database service';
        }
        $databaseService = new DatabaseService();
        $databaseService->find($deployment->database_service_id);
        if (!$databaseService->exists()) {
            return 'Database service no longer exists';
        }

        $namespaceStep = new NamespaceStep();
        $namespaceIsNotUsable = $namespaceStep->reasonItCannotBeUsed($deployment);
        if ($namespaceIsNotUsable !== null) {
            return $namespaceIsNotUsable;
        }

        return null;
    }

    public function startDeployCommand(Deployment $deployment, ?string $reason = null): void {
        $resource = $this->getResource($deployment, true);
        if ($resource->exists()) {
            try {
                Data::debug('migration resource exists, deleting now.');
                /** @var K8sJob $existing */
                $existing = $resource->get();
                $existing->delete(['pretty' => 1], 0);

                // Wait for completion
                $stop = 10;
                do {
                    $existing = $resource->get();
                    Data::debug('resource still exists?', $existing->exists());
                } while($existing->exists() && $stop-- > 0 && sleep(2) === 0);
            } catch (\Exception $e) {
                // Keep going.
            }
        }

        $migrationJob = new MigrationJob();
        $migrationJob->deployment_id = $deployment->id;
        $migrationJob->save();
        $migrationJob->updateStatus(\MigrationJobStatusTypes::Deploying);

        // Extract container, add environment variable, reattach container and template
        $template = $resource->getTemplate();
        /** @var Container $container */
        $container = $template->getContainers()[0];
        $container->addEnv('MIGRATION_JOB_ID', (string)$migrationJob->id);
        $container->addToAttribute('env', [
            'name' => self::CallbackTokenVariable,
            'valueFrom' => ['secretKeyRef' => [
                'name' => $this->workloadSecret->name,
                'key' => $this->workloadSecret->add($deployment->name, self::CallbackTokenVariable, $migrationJob->issueCallbackToken()),
            ]],
        ]);
        $template->setContainers([$container]);
        $resource->setTemplate(KubeHelper::AsTemplate($template));

        $migrationJob->image = $container->getAttribute('image');
        $migrationJob->command = $deployment->findDeploymentSpecification()->database_migration_command;
        $migrationJob->save();

        // Created rather than applied: the job of the last run was deleted above.
        $this->workloadSecret->applyWith($resource, $deployment, static fn (K8sJob $job) => $job->create(), removeUnused: false);
    }

    public function startTerminateCommand(Deployment $deployment): void {
        $resource = $this->getResource($deployment, true);
        $resource->synced();
        $resource->delete();
    }

    public function getKubernetesEvents(Deployment $deployment): array {
        $resource = $this->getResource($deployment, true);
        $events = [];
        /** @var K8sEvent $event */
        foreach ($resource->getEvents() as $event) {
            $events[] = [
                'count' => $event->getAttribute('count'),
                'type' => $event->getAttribute('type'),
                'reason' => $event->getAttribute('reason'),
                'date' => date('Y-m-d H:i:s', strtotime_($event->getAttribute('lastTimestamp'))),
                'from' => $event->getAttribute('source')['component'] ?? '',
                'message' => $event->getAttribute('message'),
            ];
        }
        return $events;
    }

    public function getKubernetesStatus(Deployment $deployment): array {
        /** @var K8sJob $resource */
        $resource = $this->getResource($deployment, true)->get();
        // An empty list, not null: a resource whose controller has not written a status yet
        // - or a kind that has none at all, like a ConfigMap - would otherwise fail the
        // `array` this returns, and the whole status panel died on it.
        return $resource->getAttribute('status') ?? [];
    }

    /**
     * @throws \Exception
     */
    /**
     * The Secret the last getResource() put the secret variables in - see DeploymentStep.
     */
    protected ?WorkloadSecret $workloadSecret = null;

    protected function getResource(Deployment $deployment, bool $auth = false): K8sJob {
        $spec = $deployment->findDeploymentSpecification();
        $this->workloadSecret = $secret = WorkloadSecret::For($deployment->name, 'job');

        $containerImage = new ContainerImage();

        if ($spec->database_migration_container_image_id) {
            $containerImage->find($spec->database_migration_container_image_id);
            $tag = match ($spec->database_migration_container_image_tag_policy) {
                \ContainerImageTagPolicies::MatchDeployment => $deployment->version,
                \ContainerImageTagPolicies::Static => $spec->database_migration_container_image_tag_value,
                \ContainerImageTagPolicies::Default => $containerImage->default_tag,
            };
        } else {
            $containerImage->find($spec->container_image_id);
            $tag = $deployment->version;
        }

        $container = new Container();
        $container
            ->setAttribute('name', $deployment->name)
            ->setImage($containerImage->url, $tag)
            ->setAttribute('imagePullPolicy', $deployment->image_pull_policy)
            ->setAttribute('command', [
                '/bin/sh'
            ])
            ->setAttribute('args', [
                '-c',

                // Tell KSO about migration job started. Only a status, so the migration runs
                // whether or not kso answers (#42), and the retries are kept short: waiting
                // on it would hold up the release it is reporting on.
                'curl --connect-timeout 5 --max-time 30 --retry 5 --retry-delay 5 --retry-max-time 60 -i -v -X PUT ' . $this->getMigrationStartedUrl() . ' ' . self::CallbackTokenHeaderArgument

                // Perform migration
                . ' ; ' . $spec->database_migration_command

                // Tell KSO about migration job ended
                . ' | curl --connect-timeout 5 --max-time 300 --retry 10 --retry-delay 5 --retry-max-time 300 -i -v -X PUT --data-binary @- ' . $this->getMigrationEndedUrl() . ' ' . self::CallbackTokenHeaderArgument,
            ])
            ->addEnv('ENVIRONMENT', \Environments::Development)
            ->addEnv('BASE_URL', $deployment->getUrl(true, true));

        // Security Context
        if (strlen($containerImage->security_context_run_as_user) > 0) {
            $container->setAttribute('securityContext.runAsUser', (int)$containerImage->security_context_run_as_user);
        }
        if (strlen($containerImage->security_context_run_as_group) > 0) {
            $container->setAttribute('securityContext.runAsGroup', (int)$containerImage->security_context_run_as_group);
        }
        $container->setAttribute('securityContext.allowPrivilegeEscalation', (bool)$containerImage->security_context_allow_privilege_escalation);
        $container->setAttribute('securityContext.readOnlyRootFilesystem', (bool)$containerImage->security_context_read_only_root_filesystem);

        // Init Containers
        $initContainers = [];
        /** @var DeploymentSpecificationInitContainer $deploymentSpecificationInitContainers */
        $deploymentSpecificationInitContainers = (new DeploymentSpecificationInitContainerModel())
            ->includeRelated([InitContainerModel::class, ContainerImageModel::class])
            ->where('deployment_specification_id', $spec->id)
            ->where('include_in_migration_job', true)
            ->orderBy('position', 'asc')
            ->find();
        $podImages = [$containerImage];
        foreach ($deploymentSpecificationInitContainers as $deploymentSpecificationInitContainer) {
            $initContainers[] = $deploymentSpecificationInitContainer->init_container->toKubernetesResource($deployment, $secret);
            $podImages[] = $deploymentSpecificationInitContainer->init_container->container_image;
        }

        ContainerEnvironment::ofDeployment($deployment)->applyTo($container, $secret);

        $volumes = [];
        /** @var DeploymentVolume $deploymentVolumes */
        $deploymentVolumes = (new DeploymentVolumeModel())
            ->where('deployment_id', $deployment->id)
            ->find();
        foreach ($deploymentVolumes as $deploymentVolume) {
            $volume = new Volume();
            $volume
                ->setAttribute('name', $deployment->name)
                ->setAttribute('persistentVolumeClaim', [
                    'claimName' => $deployment->name,
                ]);

            $container->addMountedVolume($volume->mountTo($deploymentVolume->mount_path, $deploymentVolume->sub_path));

            $volumes[] = $volume;
        }
        /** @var DeploymentSpecificationVolume $deploymentSpecificationVolumes */
        $deploymentSpecificationVolumes = (new DeploymentSpecificationVolumeModel())
            ->where('deployment_specification_id', $spec->id)
            ->find();
        foreach ($deploymentSpecificationVolumes as $deploymentSpecificationVolume) {
            $volume = new Volume();
            $volume
                ->setAttribute('name', $deployment->name)
                ->setAttribute('persistentVolumeClaim', [
                    'claimName' => $deployment->name,
                ]);

            $container->addMountedVolume($volume->mountTo(
                $deploymentSpecificationVolume->mount_path,
                $deploymentSpecificationVolume->getCompiledSubPath($deployment)
            ));

            $volumes[] = $volume;
        }

        $template = new K8sPod();
        $template
            ->setAttribute('metadata', [
                'labels' => [
                    'app' => $deployment->name,
                    'role' => 'migration',
                ],
            ])
            ->setContainers([
                $container
            ])
            ->neverRestart();

        if (strlen($containerImage->security_context_fs_group) > 0) {
            $template->setSpec('securityContext.fsGroup', (int)$containerImage->security_context_fs_group);
        }

        $imagePullSecrets = ImagePullSecrets::of(...$podImages);
        if (count($imagePullSecrets) > 0) {
            $template->setSpec('imagePullSecrets', $imagePullSecrets);
        }

        if (count($initContainers) > 0) {
            $template->setInitContainers($initContainers);
        }

        if (count($volumes) > 0) {
            $template->setVolumes($volumes);
        }

        if ($spec->hasDeploymentStep($deployment, ServiceAccountStep::class)) {
            $template->setSpec('serviceAccountName', $deployment->name);
        }

        $resource = new K8sJob();
        $resource
            ->setName($deployment->name)
            ->setNamespace($deployment->namespace)
            ->setTemplate(KubeHelper::AsTemplate($template))
            ->setSpec('activeDeadlineSeconds', 21600);

        if ($auth) {
            $auth = new KubeAuth();
            $resource->onCluster($auth->authenticate());
        }

        return $resource;
    }

    private function getMigrationStartedUrl(): string {
        if (getenv('DEV_REMOTE_BASE_URL')) {
            $domain = getenv('DEV_REMOTE_BASE_URL');
        } else {
            $domain = KubeHelper::GetMyHostname() . '.' . KubeHelper::GetMyNamespace();
        }
        return "$domain/api/migration-jobs/$(MIGRATION_JOB_ID)/started";
    }

    private function getMigrationEndedUrl(): string {
        if (getenv('DEV_REMOTE_BASE_URL')) {
            $domain = getenv('DEV_REMOTE_BASE_URL');
        } else {
            $domain = KubeHelper::GetMyHostname() . '.' . KubeHelper::GetMyNamespace();
        }
        return "$domain/api/migration-jobs/$(MIGRATION_JOB_ID)/ended";
    }

}
