<?php namespace App\Libraries\DeploymentSteps;

use App\Entities\ContainerImage;
use App\Entities\DatabaseService;
use App\Entities\Deployment;
use App\Entities\DeploymentSpecificationVolume;
use App\Entities\DeploymentVolume;
use App\Entities\MigrationJob;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepHelper;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepLevels;
use App\Libraries\DeploymentSteps\Helpers\DeploymentSteps;
use App\Libraries\DeploymentSteps\Helpers\DeploymentStepTriggers;
use App\Libraries\Kubernetes\SecurityContext;
use App\Libraries\Kubernetes\ContainerEnvironment;
use App\Libraries\Kubernetes\SecretPreview;
use App\Libraries\Kubernetes\WorkloadSecret;
use App\Libraries\Kubernetes\ImagePullSecrets;
use App\Libraries\Kubernetes\KubeAuth;
use App\Libraries\Kubernetes\KubeHelper;
use App\Models\DeploymentSpecificationVolumeModel;
use App\Models\DeploymentVolumeModel;
use DebugTool\Data;
use RenokiCo\PhpK8s\Exceptions\KubernetesAPIException;
use RenokiCo\PhpK8s\Instances\Container;
use RenokiCo\PhpK8s\Instances\Volume;
use RenokiCo\PhpK8s\Kinds\K8sEvent;
use RenokiCo\PhpK8s\Kinds\K8sJob;
use RenokiCo\PhpK8s\Kinds\K8sPod;
use App\Libraries\Kubernetes\WritablePaths;

class MigrationJobStep extends BaseDeploymentStep {

    /**
     * How the watcher of a new job is started - see `MigrationJobWatcher`. The test suite puts a
     * recorder here: a real start would watch outside the test, against the development database.
     *
     * @var null|\Closure(int): void
     */
    public static ?\Closure $startWatching = null;

    public function getIdentifier(): string {
        return DeploymentSteps::Migration;
    }

    public function getLevel(): string {
        return DeploymentStepLevels::Deployment;
    }

    public function getName(): string {
        return 'Migration Job';
    }

    public function getTriggers(): array {
        return [
            DeploymentStepTriggers::Deployment_Version_Updated,
            DeploymentStepTriggers::Deployment_ImagePullPolicy_Updated,
        ];
    }

    public function hasPreviewCommand(): bool {
        return true;
    }

    public function hasStatusCommand(): bool {
        return true;
    }

    public function hasDeployCommand(): bool {
        return true;
    }

    public function hasTerminateCommand(): bool {
        return true;
    }

    public function hasKubernetesEvents(): bool {
        return false;
    }

    public function hasKubernetesStatus(): bool {
        return true;
    }

    public function getSuccessStatus(Deployment $deployment): string {
        return DeploymentStepHelper::MigrationJob_Completed;
    }

    /**
     * @throws \Exception
     */
    public function getPreview(Deployment $deployment): string {
        $resource = $this->getResource($deployment, true);
        $local = $resource->toJson();

        if ($resource->exists()) {
            $exiting = $resource->get();
            $remote = json_decode($exiting->toJson(), true);
            unset($remote['metadata']['uid']);
            unset($remote['metadata']['resourceVersion']);
            unset($remote['metadata']['generation']);
            unset($remote['metadata']['creationTimestamp']);
            unset($remote['metadata']['annotations']);
            unset($remote['metadata']['managedFields']);

            // The labels the Job controller copies up from the template, plus its own
            // `controller-uid` and `job-name`. Nothing here was written by kso.
            unset($remote['metadata']['labels']);

            // This step builds a **Job**. The list used to be `spec.jobTemplate.*` with
            // `concurrencyPolicy` and the two history limits beside it - CronJob fields, on
            // a resource that has none of them, so every one of those `unset()` calls did
            // nothing. It reads like a copy of `CronjobStep::getPreview()` that was never
            // rebased.
            //
            // What did reach the diff was the Job's own defaults, filled in by the api
            // server: a preview of a migration showed half a dozen removals the user could
            // not do anything about, every single time.
            unset($remote['spec']['parallelism']);
            unset($remote['spec']['completions']);
            unset($remote['spec']['completionMode']);
            unset($remote['spec']['podReplacementPolicy']);
            unset($remote['spec']['manualSelector']);
            unset($remote['spec']['suspend']);

            // Generated by the controller from the job's uid, and kso sets no selector of
            // its own on a Job.
            unset($remote['spec']['selector']);

            // The same paths the cron job step strips, one level shallower: a Job's template
            // is `spec.template`, a CronJob's is `spec.jobTemplate.spec.template`.
            unset($remote['spec']['template']['metadata']);
            unset($remote['spec']['template']['spec']['containers'][0]['resources']);
            unset($remote['spec']['template']['spec']['containers'][0]['terminationMessagePath']);
            unset($remote['spec']['template']['spec']['containers'][0]['terminationMessagePolicy']);
            if (isset($remote['spec']['template']['spec'])) {
                $remote['spec']['template']['spec'] = KubeHelper::WithoutInitContainerDefaults($remote['spec']['template']['spec']);
            }
            unset($remote['spec']['template']['spec']['terminationGracePeriodSeconds']);
            unset($remote['spec']['template']['spec']['dnsPolicy']);
            unset($remote['spec']['template']['spec']['schedulerName']);

            // Only when kso expressed no opinion. The api server writes an empty
            // `securityContext` for a pod spec that has none, and that empty object is
            // noise - but a deployment whose image asks for an `fsGroup` does set one, and
            // stripping it then would hide a difference that matters.
            if (!isset(json_decode($local, true)['spec']['template']['spec']['securityContext'])) {
                unset($remote['spec']['template']['spec']['securityContext']);
            }

            unset($remote['status']);
        }

        return json_encode(SecretPreview::of(
            $local,
            $remote ?? null,
            $this->workloadSecret,
            $deployment,
            $this->workloadSecret->remoteData($deployment, (new KubeAuth())->authenticate())
        ));
    }

    /**
     * @throws KubernetesAPIException
     * @throws \Exception
     */
    public function getStatus(Deployment $deployment): string {
        $resource = $this->getResource($deployment, true);
        if (!$resource->exists()) {
            return DeploymentStepHelper::MigrationJob_NotFound;
        }

        try {
            /** @var K8sJob $resource */
            $resource = $resource->get();
        } catch (KubernetesAPIException $e) {
            // Asking whether it is there and then asking for it are two calls, and a job
            // being cleaned up disappears between them - which is the ordinary case right
            // after a terminate. A status call is not the place to throw about that.
            if ($e->getCode() === KubeHelper::NotFoundCode) {
                return DeploymentStepHelper::MigrationJob_NotFound;
            }

            throw $e;
        }

        if ($resource->getStatus('completionTime')) {
            return DeploymentStepHelper::MigrationJob_Completed;
        }

        // With the migration's own exit code in the pod, a failing migration fails its Job - and
        // is not running for the rest of its days. The migration job's row says why.
        foreach ($resource->getStatus('conditions') ?? [] as $condition) {
            if (($condition['type'] ?? '') === 'Failed' && ($condition['status'] ?? '') === 'True') {
                return DeploymentStepHelper::MigrationJob_Failed;
            }
        }

        return DeploymentStepHelper::MigrationJob_Running;
    }

    public function validateDeployCommand(Deployment $deployment): ?string {
        if (strlen($deployment->name) == 0) {
            return 'Missing name';
        }
        if (strlen($deployment->namespace) == 0) {
            return 'Missing namespace';
        }
        if (strlen($deployment->image) == 0) {
            return 'Missing image';
        }
        if (strlen($deployment->version) == 0) {
            return 'Missing version';
        }

        if (!$deployment->database_service_id) {
            return 'Missing database service';
        }
        $databaseService = new DatabaseService();
        $databaseService->find($deployment->database_service_id);
        if (!$databaseService->exists()) {
            return 'Database service no longer exists';
        }

        $namespaceStep = new NamespaceStep();
        $namespaceIsNotUsable = $namespaceStep->reasonItCannotBeUsed($deployment);
        if ($namespaceIsNotUsable !== null) {
            return $namespaceIsNotUsable;
        }

        return null;
    }

    public function startDeployCommand(Deployment $deployment, ?string $reason = null): void {
        $resource = $this->getResource($deployment, true);
        if ($resource->exists()) {
            try {
                Data::debug('migration resource exists, deleting now.');
                /** @var K8sJob $existing */
                $existing = $resource->get();
                $existing->delete(['pretty' => 1], 0);

                // Wait for completion
                $stop = 10;
                do {
                    $existing = $resource->get();
                    Data::debug('resource still exists?', $existing->exists());
                } while($existing->exists() && $stop-- > 0 && sleep(2) === 0);
            } catch (\Exception $e) {
                // Keep going.
            }
        }

        $migrationJob = new MigrationJob();
        $migrationJob->deployment_id = $deployment->id;
        $migrationJob->save();
        $migrationJob->updateStatus(\MigrationJobStatusTypes::Deploying);

        // Extract container, add environment variable, reattach container and template. The id
        // is how the watcher tells this run's pod from the last one's: both are named after the
        // deployment.
        $template = $resource->getTemplate();
        /** @var Container $container */
        $container = $template->getContainers()[0];
        $container->addEnv('MIGRATION_JOB_ID', (string)$migrationJob->id);
        $template->setContainers([$container]);
        $resource->setTemplate(KubeHelper::AsTemplate($template));

        $migrationJob->image = $container->getAttribute('image');
        $migrationJob->command = $deployment->findDeploymentSpecification()->database_migration_command;
        $migrationJob->save();

        // Created rather than applied: the job of the last run was deleted above.
        $this->workloadSecret->applyWith($resource, $deployment, static fn (K8sJob $job) => $job->create(), removeUnused: false);

        (self::$startWatching ?? fn (int $id) => self::startWatchingInTheBackground($id, (int) $deployment->id))((int) $migrationJob->id);
    }

    /**
     * Started and left, as Jobby starts a cron job: the deploy answers at once, and the job's
     * row follows the migration. The cron job picks the job up if this goes with its kso pod.
     * One output file per deployment, overwritten by its next run, rather than one per job kept
     * for as long as the pod lives.
     */
    private static function startWatchingInTheBackground(int $migrationJobId, int $deploymentId): void {
        $command = 'php ' . ROOTPATH . "spark app:watch-migration-job {$migrationJobId} > /tmp/migration_job_{$deploymentId}.txt 2>&1";
        exec('nohup sh -c ' . escapeshellarg($command) . ' > /dev/null 2>&1 &');
    }

    public function startTerminateCommand(Deployment $deployment): void {
        $resource = $this->getResource($deployment, true);
        $resource->synced();
        $resource->delete();
    }

    public function getKubernetesEvents(Deployment $deployment): array {
        $resource = $this->getResource($deployment, true);
        $events = [];
        /** @var K8sEvent $event */
        foreach ($resource->getEvents() as $event) {
            $events[] = [
                'count' => $event->getAttribute('count'),
                'type' => $event->getAttribute('type'),
                'reason' => $event->getAttribute('reason'),
                'date' => date('Y-m-d H:i:s', strtotime_($event->getAttribute('lastTimestamp'))),
                'from' => $event->getAttribute('source')['component'] ?? '',
                'message' => $event->getAttribute('message'),
            ];
        }
        return $events;
    }

    public function getKubernetesStatus(Deployment $deployment): array {
        /** @var K8sJob $resource */
        $resource = $this->getResource($deployment, true)->get();
        // An empty list, not null: a resource whose controller has not written a status yet
        // - or a kind that has none at all, like a ConfigMap - would otherwise fail the
        // `array` this returns, and the whole status panel died on it.
        return $resource->getAttribute('status') ?? [];
    }

    /**
     * @throws \Exception
     */
    /**
     * The Secret the last getResource() put the secret variables in - see DeploymentStep.
     */
    protected ?WorkloadSecret $workloadSecret = null;

    protected function getResource(Deployment $deployment, bool $auth = false): K8sJob {
        $spec = $deployment->findDeploymentSpecification();
        $this->workloadSecret = $secret = WorkloadSecret::For($deployment->name, 'job');

        $containerImage = new ContainerImage();

        if ($spec->database_migration_container_image_id) {
            $containerImage->find($spec->database_migration_container_image_id);
            $tag = match ($spec->database_migration_container_image_tag_policy) {
                \ContainerImageTagPolicies::MatchDeployment => $deployment->version,
                \ContainerImageTagPolicies::Static => $spec->database_migration_container_image_tag_value,
                \ContainerImageTagPolicies::Default => $containerImage->default_tag,
            };
        } else {
            $containerImage->find($spec->container_image_id);
            $tag = $deployment->version;
        }

        $container = new Container();
        $container
            ->setAttribute('name', $deployment->name)
            ->setImage($containerImage->url, $tag)
            ->setAttribute('imagePullPolicy', $deployment->image_pull_policy)
            ->setAttribute('command', [
                '/bin/sh'
            ])
            // The migration and nothing else. kso reads its start, its end, its exit code and its
            // log from the cluster (`MigrationJobWatcher`), so the image needs no curl and the
            // pod ends with the migration's own exit code.
            ->setAttribute('args', [
                '-c',
                $spec->database_migration_command,
            ])
            ->addEnv('ENVIRONMENT', \Environments::Development)
            ->addEnv('BASE_URL', $deployment->getUrl(true, true));

        // Security Context - the image's, and what the specification opts into
        SecurityContext::ApplyToContainer($container, $containerImage, $spec);

        // Init Containers - the ones the specification includes in the migration job, sidecars
        // among them. Kept rather than filtered: Kubernetes stops a sidecar when the job's own
        // container is done, so the Job still completes, and a sidecar the migration needs - a
        // database proxy, say - is what the job would otherwise lack. One only the app uses, such
        // as a push server, is left out the way any init container is: not included in the job.
        $initContainers = [];
        $deploymentSpecificationInitContainers = $spec->findInitContainersInStartOrder(onlyForTheMigrationJob: true);
        $podImages = [$containerImage];
        foreach ($deploymentSpecificationInitContainers as $deploymentSpecificationInitContainer) {
            $initContainers[] = $deploymentSpecificationInitContainer->init_container->toKubernetesResource($deployment, $secret);
            $podImages[] = $deploymentSpecificationInitContainer->init_container->container_image;
        }

        ContainerEnvironment::ofDeployment($deployment)->applyTo($container, $secret);

        $volumes = [];
        /** @var DeploymentVolume $deploymentVolumes */
        $deploymentVolumes = (new DeploymentVolumeModel())
            ->where('deployment_id', $deployment->id)
            ->find();
        foreach ($deploymentVolumes as $deploymentVolume) {
            $volume = new Volume();
            $volume
                ->setAttribute('name', $deployment->name)
                ->setAttribute('persistentVolumeClaim', [
                    'claimName' => $deployment->name,
                ]);

            $container->addMountedVolume($volume->mountTo($deploymentVolume->mount_path, $deploymentVolume->sub_path));

            $volumes[] = $volume;
        }
        /** @var DeploymentSpecificationVolume $deploymentSpecificationVolumes */
        $deploymentSpecificationVolumes = (new DeploymentSpecificationVolumeModel())
            ->where('deployment_specification_id', $spec->id)
            ->find();
        foreach ($deploymentSpecificationVolumes as $deploymentSpecificationVolume) {
            $volume = new Volume();
            $volume
                ->setAttribute('name', $deployment->name)
                ->setAttribute('persistentVolumeClaim', [
                    'claimName' => $deployment->name,
                ]);

            $container->addMountedVolume($volume->mountTo(
                $deploymentSpecificationVolume->mount_path,
                $deploymentSpecificationVolume->getCompiledSubPath($deployment)
            ));

            $volumes[] = $volume;
        }

        $template = new K8sPod();
        $template
            ->setAttribute('metadata', [
                'labels' => [
                    'app' => $deployment->name,
                    'role' => 'migration',
                ],
            ])
            ->setContainers([
                $container
            ])
            ->neverRestart();

        $fsGroup = SecurityContext::FsGroup($containerImage, $spec);
        if ($fsGroup !== null) {
            $template->setSpec('securityContext.fsGroup', $fsGroup);
        }

        $imagePullSecrets = ImagePullSecrets::of(...$podImages);
        if (count($imagePullSecrets) > 0) {
            $template->setSpec('imagePullSecrets', $imagePullSecrets);
        }

        if (count($initContainers) > 0) {
            $template->setInitContainers($initContainers);
        }

        $volumes = [...$volumes, ...WritablePaths::Volumes([$container, ...$initContainers], $spec)];
        if (count($volumes) > 0) {
            $template->setVolumes($volumes);
        }

        if ($spec->hasDeploymentStep($deployment, ServiceAccountStep::class)) {
            $template->setSpec('serviceAccountName', $deployment->name);
        }

        $resource = new K8sJob();
        $resource
            ->setName($deployment->name)
            ->setNamespace($deployment->namespace)
            ->setTemplate(KubeHelper::AsTemplate($template))
            ->setSpec('activeDeadlineSeconds', 21600)
            // Once. The migration's exit code is the pod's now, and Kubernetes' default of 6 would
            // run a failing migration seven times over a half-migrated database.
            ->setSpec('backoffLimit', 0);

        if ($auth) {
            $auth = new KubeAuth();
            $resource->onCluster($auth->authenticate());
        }

        return $resource;
    }

}
