import { createVuetify } from 'vuetify'
import { aliases, fa } from 'vuetify/iconsets/fa'
// Only the components the templates use. All of them was a quarter of what the
// browser had to load before anything was drawn. A component missing here renders as an
// unknown element with a warning in the console - add it to this list.
import {
    VAlert,
    VApp,
    VAutocomplete,
    VBadge,
    VBottomNavigation,
    VBottomSheet,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VCol,
    VCombobox,
    VDataTable,
    VDataTableServer,
    VDialog,
    VDivider,
    VExpandTransition,
    VFooter,
    VForm,
    VIcon,
    VImg,
    VList,
    VListGroup,
    VListItem,
    VListItemSubtitle,
    VListItemTitle,
    VListSubheader,
    VMain,
    VMenu,
    VNavigationDrawer,
    VProgressCircular,
    VProgressLinear,
    VRow,
    VSelect,
    VSnackbar,
    VSpacer,
    VSwitch,
    VSystemBar,
    VTab,
    VTable,
    VTabs,
    VTabsWindow,
    VTabsWindowItem,
    VTextField,
    VTextarea,
    VToolbar,
    VToolbarTitle,
    VTooltip,
    VWindow,
    VWindowItem,
} from 'vuetify/components'
import * as directives from 'vuetify/directives'

const customLightTheme = {
    dark: false,
    colors: {
        background: '#e9f0f2',
        surface: '#e9f0f2',
        primary: '#1a3b46',
        'primary-darken-1': '#0a1a1f',
        secondary: '#2e92a3',
        'secondary-darken-1': '#03504b',
        error: '#B00020',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#FB8C00',
    },
}

export default createVuetify({
    components: {
        VAlert,
        VApp,
        VAutocomplete,
        VBadge,
    VBottomNavigation,
    VBottomSheet,
        VBtn,
        VCard,
        VCardActions,
        VCardText,
        VCardTitle,
        VCheckbox,
        VChip,
        VCol,
        VCombobox,
        VDataTable,
        VDataTableServer,
        VDialog,
        VDivider,
        VExpandTransition,
        VFooter,
        VForm,
        VIcon,
        VImg,
        VList,
        VListGroup,
        VListItem,
        VListItemSubtitle,
        VListItemTitle,
        VListSubheader,
        VMain,
        VMenu,
        VNavigationDrawer,
        VProgressCircular,
        VProgressLinear,
        VRow,
        VSelect,
        VSnackbar,
        VSpacer,
        VSwitch,
        VSystemBar,
        VTab,
        VTable,
        VTabs,
        VTabsWindow,
        VTabsWindowItem,
        VTextField,
        VTextarea,
        VToolbar,
        VToolbarTitle,
        VTooltip,
        VWindow,
        VWindowItem,
    },
    directives,
    // On a phone every table is a list of cards, a row each, its columns as lines: five to eight
    // columns do not fit beside each other in 375px, and a row's buttons ended off the edge.
    // The rows and headers decide for themselves, so each part is told - and `mobile` must be
    // null, not its default false, or the breakpoint is never looked at.
    defaults: {
        VDataTable: {mobile: null, mobileBreakpoint: 'sm'},
        VDataTableServer: {mobile: null, mobileBreakpoint: 'sm'},
        VDataTableRows: {mobile: null, mobileBreakpoint: 'sm'},
        VDataTableHeaders: {mobile: null, mobileBreakpoint: 'sm'},
    },
    theme: {
        defaultTheme: 'customLightTheme',
        themes: {
            customLightTheme,
        }
    },
    icons: {
        defaultSet: 'fa',
        aliases: {
            ... aliases,
            next: 'fa fa-chevron-right',
            prev: 'fa fa-chevron-left',
            last: 'fa fa-chevrons-right',
            first: 'fa fa-chevrons-left',
            dropdown: 'fa fa-circle-chevron-down',
        },
        sets: {
            fa,
        }
    },
});
