apiVersion: v1
kind: Service
metadata:
  name: {{ include "kso.fullname" . }}
  labels:
    {{- include "kso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: "http"
      protocol: TCP
      name: http
    - port: 9100
      targetPort: "9100"
      protocol: TCP
      name: ratchet
  selector:
    {{- include "kso.selectorLabels" . | nindent 4 }}
