import { writeFileSync } from "fs";

const util = require("util");
const exec = util.promisify(require("child_process").exec);

// https://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application

async function createVersionsFile(filename: string) {
  const revision = (await exec("git rev-parse --short HEAD")).stdout
    .toString()
    .trim();
  const branch = (await exec("git rev-parse --abbrev-ref HEAD")).stdout
    .toString()
    .trim();

  console.log(`revision: '${revision}', branch: '${branch}'`);

  const content = `
// *** This file is automatically generated by git.version.ts script. Version no. is taken from package.json *** 
export const versions = {
    revision: "${revision}",
    branch: "${branch}",
    version: "_VERSION_",
    project_id: "_PROJECT_ID_"
};`;

  writeFileSync(filename, content, { encoding: "utf8" });
}

createVersionsFile("src/versions.ts");
